#pragma kernel FluidCompute

StructuredBuffer<float4> _RawCells; // (vx, vy, density, 0)

RWTexture2D<float2> _VelocityRT; 
RWTexture2D<float4> _ShadedRT; 

uint2 _TexSize;

[numthreads(16, 16, 1)]
void FluidCompute(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= _TexSize.x || id.y >= _TexSize.y) return;
    uint idx = id.y * _TexSize.x + id.x;

    float4 cell = _RawCells[idx];
    float2 vel = cell.xy;
    float d = cell.z;

    _VelocityRT[id.xy] = vel;
    _ShadedRT[id.xy] = float4(vel, d, 1);
}
